export interface ProfileUser {
  uid: any,
  email?: any,
  firstName?: any,
  photoURL?: any,
  lastName?: any,
  time?: any,
  entryTime?: any,
  exitTime?: any,
  numberPlate?: any,
  location?: any,
  password?:any,
  spouse?: any,
  religion?: any,
  doB?: any,
  displayName?: any,
  phone?: any,
  placeOfWork?:any,
}
